name: Tinode Dev Deployment

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Deploy Tinode Dev
    uses: awr-ggl/action/.github/workflows/tinode_dev.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
