name: Tinode Dev Deployment

on:
  push:
     branches: [development]

jobs:
  deploy:
    name: Deploy to tinode-dev
    if: ${{ always() }}
    uses: awr-ggl/action/.github/workflows/tinode_dev.yml@main
    with:
      DIRECTORY_PATH: /var/www/chat/
      SERVER_IP: 10.184.15.195
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      