name: Tinode Dev Deployment

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Deploy Tinode Dev
    runs-on: biznet-gio
    steps:
      
      - name: Build binary
        run: sudo -u ubuntu bash -c 'cd /home/ubuntu/chat_to_prod; ./build-all.sh'
  
      - name: Deploy Tinode
        run: sudo supervisorctl update && sudo supervisorctl restart tinode

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
