name: Tinode Dev Deployment

on:
  push:
     branches: [development]
env:
  CHANGE_DIR: sudo ssh -i /root/.ssh/runner -tt runner@${{ secrets.SERVER_IP }} "cd ${{ secrets.DIRECTORY_PATH }};

jobs:
  deploy:
    name: Deploy Tinode Dev
    runs-on: self-hosted
    steps:
      - name: Git Pull
        run: ${{ env.CHANGE_DIR }} sudo git fetch origin; sudo git checkout development && sudo git pull"
      
      - name: Build binary
        run: ${{ env.CHANGE_DIR }} sudo ./build-all.sh"
  
      - name: Stop Tinode Service
        run: ${{ env.CHANGE_DIR }} sudo supervisorctl stop tinode"

      - name: Backup Old Binary
        run: ${{ env.CHANGE_DIR }} sudo cp /var/www/tinode-mysql-v0.22.11/tinode /var/www/tinode-mysql-v0.22.11/tinode_$(date +\%d_\%m_\%Y)"

      - name: Copy New Binary
        run: ${{ env.CHANGE_DIR }} version=\$(git describe --tags --always | sed 's/^v//') ; sudo cp binaries/\$version-mysql/tinode /var/www/tinode-mysql-v0.22.11/tinode"

      - name: Start Tinode Service
        run: ${{ env.CHANGE_DIR }} sudo supervisorctl start tinode"

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
